name: 'Pre-Prod Add Domain Users to Local Groups in VM'

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Azure Resource Group name'
        required: true
      vm_name:
        description: 'VM name'
        required: true
